// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package restaurante.Restaurante;

import restaurante.Individuos.Cliente;

/************************************************************/
/**
 * 
 */
public class Mesa {
	/**
	 * 
	 */
	public Integer nroMesa;
	/**
	 * 
	 */
	public Pedido[] pedido;
	/**
	 * 
	 */
	public Cliente cliente;
	public Integer getNroMesa() {
		return nroMesa;
	}
	public void setNroMesa(Integer nroMesa) {
		this.nroMesa = nroMesa;
	}
	public Pedido[] getPedido() {
		return pedido;
	}
	public void setPedido(Pedido[] pedido) {
		this.pedido = pedido;
	}
	public Cliente getCliente() {
		return cliente;
	}
	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}
	
	
}
