// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package restaurante.Restaurante;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Pedido {
	/**
	 * 
	 */
	public Date dataHora;
	
	public Integer nroPedido;
	
	
	public Integer getNroPedido() {
		return nroPedido;
	}
	public void setNroPedido(Integer nroPedido) {
		this.nroPedido = nroPedido;
	}
	/**
	 * 
	 */
	public Produto[] produto;
	public Date getDataHora() {
		return dataHora;
	}
	public void setDataHora(Date dataHora) {
		this.dataHora = dataHora;
	}
	public Produto[] getProduto() {
		return produto;
	}
	public void setProduto(Produto[] produto) {
		this.produto = produto;
	}
	
}
