// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package restaurante.Restaurante;

/************************************************************/
/**
 * 
 */
public class Produto {
	/**
	 * 
	 */
	public String nomeProduto;
	/**
	 * 
	 */
	public Float valorProduto;
	
	public String getNomeProduto() {
		return nomeProduto;
	}
	public void setNomeProduto(String nomeProduto) {
		this.nomeProduto = nomeProduto;
	}
	public Float getValorProduto() {
		return valorProduto;
	}
	public void setValorProduto(Float d) {
		this.valorProduto = d;
	}
	
	
}
