// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package restaurante.Administrativo;

/************************************************************/
/**
 * 
 */
public class Cargo {
	/**
	 * 
	 */
	public String nomeCargo;

	public String getNomeCargo() {
		return nomeCargo;
	}

	public void setNomeCargo(String nomeCargo) {
		this.nomeCargo = nomeCargo;
	}  
}
