// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package restaurante.Individuos;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Cliente extends Pessoa {
	/**
	 * 
	 */
	public Date dataCadastro;
	
	public void setDataCadatro(Date date) {
		this.dataCadastro = date;
	}
	
	public Date getDataCadastro() {
		return this.dataCadastro;
	}
}
