// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package restaurante.Individuos;

/************************************************************/
/**
 * 
 */
public class Pessoa {
	/**
	 * 
	 */
	public Integer cpf;
	/**
	 * 
	 */
	public String nome;
	
	public Integer getCpf() {
		return cpf;
	}
	public void setCpf(Integer cpf) {
		this.cpf = cpf;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	
	
}
